// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Y2JnRXZ-nO4h1KDBvL2IsfS9mkYtTMM',
    appId: '1:280701318686:web:58495355e029a1257ca00f',
    messagingSenderId: '280701318686',
    projectId: 'streamalert-a07d2',
    authDomain: 'streamalert-a07d2.firebaseapp.com',
    storageBucket: 'streamalert-a07d2.firebasestorage.app',
    measurementId: 'G-RW0D9Z0781',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16nf3Rj-jmHwLI2X9UYHg_vYNSzHgFUI',
    appId: '1:280701318686:android:6b026ecb284107f67ca00f',
    messagingSenderId: '280701318686',
    projectId: 'streamalert-a07d2',
    storageBucket: 'streamalert-a07d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5hmXQxV4M6hBooUUP-4bluqy25QaF5c',
    appId: '1:280701318686:ios:b485373de607b08b7ca00f',
    messagingSenderId: '280701318686',
    projectId: 'streamalert-a07d2',
    storageBucket: 'streamalert-a07d2.firebasestorage.app',
    iosBundleId: 'com.example.streamAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc5hmXQxV4M6hBooUUP-4bluqy25QaF5c',
    appId: '1:280701318686:ios:b485373de607b08b7ca00f',
    messagingSenderId: '280701318686',
    projectId: 'streamalert-a07d2',
    storageBucket: 'streamalert-a07d2.firebasestorage.app',
    iosBundleId: 'com.example.streamAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Y2JnRXZ-nO4h1KDBvL2IsfS9mkYtTMM',
    appId: '1:280701318686:web:7d2903a2c421f5817ca00f',
    messagingSenderId: '280701318686',
    projectId: 'streamalert-a07d2',
    authDomain: 'streamalert-a07d2.firebaseapp.com',
    storageBucket: 'streamalert-a07d2.firebasestorage.app',
    measurementId: 'G-32BK5LNSLH',
  );

}